// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scheduler.proto
// Protobuf C++ Version: 5.27.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_scheduler_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_scheduler_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scheduler_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scheduler_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scheduler_2eproto;
namespace scheduler {
class VehicleSchedulingRequest;
struct VehicleSchedulingRequestDefaultTypeInternal;
extern VehicleSchedulingRequestDefaultTypeInternal _VehicleSchedulingRequest_default_instance_;
}  // namespace scheduler
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace scheduler {

// ===================================================================


// -------------------------------------------------------------------

class VehicleSchedulingRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:scheduler.VehicleSchedulingRequest) */ {
 public:
  inline VehicleSchedulingRequest() : VehicleSchedulingRequest(nullptr) {}
  ~VehicleSchedulingRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VehicleSchedulingRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline VehicleSchedulingRequest(const VehicleSchedulingRequest& from) : VehicleSchedulingRequest(nullptr, from) {}
  inline VehicleSchedulingRequest(VehicleSchedulingRequest&& from) noexcept
      : VehicleSchedulingRequest(nullptr, std::move(from)) {}
  inline VehicleSchedulingRequest& operator=(const VehicleSchedulingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VehicleSchedulingRequest& operator=(VehicleSchedulingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VehicleSchedulingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VehicleSchedulingRequest* internal_default_instance() {
    return reinterpret_cast<const VehicleSchedulingRequest*>(
        &_VehicleSchedulingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VehicleSchedulingRequest& a, VehicleSchedulingRequest& b) { a.Swap(&b); }
  inline void Swap(VehicleSchedulingRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VehicleSchedulingRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VehicleSchedulingRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VehicleSchedulingRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VehicleSchedulingRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VehicleSchedulingRequest& from) { VehicleSchedulingRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VehicleSchedulingRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "scheduler.VehicleSchedulingRequest"; }

 protected:
  explicit VehicleSchedulingRequest(::google::protobuf::Arena* arena);
  VehicleSchedulingRequest(::google::protobuf::Arena* arena, const VehicleSchedulingRequest& from);
  VehicleSchedulingRequest(::google::protobuf::Arena* arena, VehicleSchedulingRequest&& from) noexcept
      : VehicleSchedulingRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRoadsideIdFieldNumber = 2,
    kAreaIdFieldNumber = 1,
  };
  // string roadsideId = 2;
  void clear_roadsideid() ;
  const std::string& roadsideid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_roadsideid(Arg_&& arg, Args_... args);
  std::string* mutable_roadsideid();
  PROTOBUF_NODISCARD std::string* release_roadsideid();
  void set_allocated_roadsideid(std::string* value);

  private:
  const std::string& _internal_roadsideid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_roadsideid(
      const std::string& value);
  std::string* _internal_mutable_roadsideid();

  public:
  // uint32 areaId = 1;
  void clear_areaid() ;
  ::uint32_t areaid() const;
  void set_areaid(::uint32_t value);

  private:
  ::uint32_t _internal_areaid() const;
  void _internal_set_areaid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:scheduler.VehicleSchedulingRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      53, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_VehicleSchedulingRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VehicleSchedulingRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr roadsideid_;
    ::uint32_t areaid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scheduler_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VehicleSchedulingRequest

// uint32 areaId = 1;
inline void VehicleSchedulingRequest::clear_areaid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.areaid_ = 0u;
}
inline ::uint32_t VehicleSchedulingRequest::areaid() const {
  // @@protoc_insertion_point(field_get:scheduler.VehicleSchedulingRequest.areaId)
  return _internal_areaid();
}
inline void VehicleSchedulingRequest::set_areaid(::uint32_t value) {
  _internal_set_areaid(value);
  // @@protoc_insertion_point(field_set:scheduler.VehicleSchedulingRequest.areaId)
}
inline ::uint32_t VehicleSchedulingRequest::_internal_areaid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.areaid_;
}
inline void VehicleSchedulingRequest::_internal_set_areaid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.areaid_ = value;
}

// string roadsideId = 2;
inline void VehicleSchedulingRequest::clear_roadsideid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roadsideid_.ClearToEmpty();
}
inline const std::string& VehicleSchedulingRequest::roadsideid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:scheduler.VehicleSchedulingRequest.roadsideId)
  return _internal_roadsideid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VehicleSchedulingRequest::set_roadsideid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roadsideid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:scheduler.VehicleSchedulingRequest.roadsideId)
}
inline std::string* VehicleSchedulingRequest::mutable_roadsideid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_roadsideid();
  // @@protoc_insertion_point(field_mutable:scheduler.VehicleSchedulingRequest.roadsideId)
  return _s;
}
inline const std::string& VehicleSchedulingRequest::_internal_roadsideid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roadsideid_.Get();
}
inline void VehicleSchedulingRequest::_internal_set_roadsideid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roadsideid_.Set(value, GetArena());
}
inline std::string* VehicleSchedulingRequest::_internal_mutable_roadsideid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roadsideid_.Mutable( GetArena());
}
inline std::string* VehicleSchedulingRequest::release_roadsideid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:scheduler.VehicleSchedulingRequest.roadsideId)
  return _impl_.roadsideid_.Release();
}
inline void VehicleSchedulingRequest::set_allocated_roadsideid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roadsideid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.roadsideid_.IsDefault()) {
          _impl_.roadsideid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:scheduler.VehicleSchedulingRequest.roadsideId)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace scheduler


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_scheduler_2eproto_2epb_2eh
